# rule identifiers to exclude from running
disabled_rules:
  - class_delegate_protocol
  - trailing_whitespace
  - weak_delegate
  - implicit_getter


# rule identifiers to opt in
opt_in_rules:
  - closure_end_indentation
  - force_unwrapping
  - fatal_error_message


# special configuration for rules 
file_length:
  warning: 400
  error: 1000

function_body_length:
  warning: 40
  error: 100

function_parameter_count:
  warning: 5
  error: 8

colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false

line_length:
  warning: 180
  error: 200
  ignores_urls: false
  ignores_function_declarations: false
  ignores_comments: false

large_tuple:
  warning: 3
  error: 4

identifier_name:
  min_length: # only min_length
    error: 1 # only error
  excluded: # excluded via string array
    - id
    - iD
    - id
    - URL
    - T
